site_name: pinax-blog
pages:
- [index.md, Home]
- [usage.md, Usage]
- [templates.md, Templates]
- [customize-admin.md, Customize Admin]
- [changelog.md, Change Log]
theme: readthedocs
repo_url: https://github.com/pinax/pinax-blog
site_description: "documentation for pinax-blog, a blog app for Django sites"
site_author: "Pinax Team"
markdown_extensions: [admonition]
